services:
  modulemonolith.api:
    image: ${DOCKER_REGISTRY-}modulemonolithapi
    container_name: ModuleMonolith.Api
    build:
      context: .
      dockerfile: source/Api/ModuleMonolith.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  modulemonolith.database:
    image: postgres:latest
    container_name: ModuleMonolith.Database
    environment:
      - POSTGRES_DB=modulemonolith
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5434:5432

  modulemonolith.seq:
    image: datalust/seq:latest
    container_name: ModuleMonolith.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:5341
      - 8081:80

  evently.redis:
    image: redis:latest
    container_name: ModuleMonolith.Redis
    restart: always
    ports:
      - 6379:6379


