// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ModuleMonolith.Modules.Codes.Api.Database.Migrations
{
    /// <inheritdoc />
    public partial class InitMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "codes");

            migrationBuilder.CreateTable(
                name: "codes",
                schema: "codes",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    value = table.Column<string>(type: "text", nullable: false),
                    is_validated = table.Column<bool>(type: "boolean", nullable: false),
                    is_defeted = table.Column<bool>(type: "boolean", nullable: false),
                    printing_status = table.Column<int>(type: "integer", nullable: false),
                    aggregating_status = table.Column<int>(type: "integer", nullable: false),
                    printed_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    validated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    defected_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    aggregated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_codes", x => x.id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "codes",
                schema: "codes");
        }
    }
}
