// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuleMonolith.Modules.Codes.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModuleMonolith.Modules.Codes.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CodesDbContext))]
    [Migration("20241017142043_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("codes")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModuleMonolith.Modules.Codes.Domain.Codes.Code", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AggregatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aggregated_at_utc");

                    b.Property<int>("AggregatingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("aggregating_status");

                    b.Property<DateTime?>("DefectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("defected_at_utc");

                    b.Property<bool>("IsDefeted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_defeted");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_validated");

                    b.Property<DateTime?>("PrintedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printed_at_utc");

                    b.Property<int>("PrintingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("printing_status");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_codes");

                    b.ToTable("codes", "codes");
                });
#pragma warning restore 612, 618
        }
    }
}
